import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import Nav from "@/components/home/appHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "StarWars",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <Nav />
          {children}
        </body>
      </Providers>
    </html>
  );
}
